<?php

use Illuminate\Database\Seeder;
use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->delete();

        $data = [
			['id' => 1101, 'province_id' => 1, 'nm_city' => 'KABUPATEN SIMEULUE'],
			['id' => 1102, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH SINGKIL'],
			['id' => 1103, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH SELATAN'],
			['id' => 1104, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH TENGGARA'],
			['id' => 1105, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH TIMUR'],
			['id' => 1106, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH TENGAH'],
			['id' => 1107, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH BARAT'],
			['id' => 1108, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH BESAR'],
			['id' => 1109, 'province_id' => 1, 'nm_city' => 'KABUPATEN PIDIE'],
			['id' => 1110, 'province_id' => 1, 'nm_city' => 'KABUPATEN BIREUEN'],
			['id' => 1111, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH UTARA'],
			['id' => 1112, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH BARAT DAYA'],
			['id' => 1113, 'province_id' => 1, 'nm_city' => 'KABUPATEN GAYO LUES'],
			['id' => 1114, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH TAMIANG'],
			['id' => 1115, 'province_id' => 1, 'nm_city' => 'KABUPATEN NAGAN RAYA'],
			['id' => 1116, 'province_id' => 1, 'nm_city' => 'KABUPATEN ACEH JAYA'],
			['id' => 1117, 'province_id' => 1, 'nm_city' => 'KABUPATEN BENER MERIAH'],
			['id' => 1118, 'province_id' => 1, 'nm_city' => 'KABUPATEN PIDIE JAYA'],
			['id' => 1171, 'province_id' => 1, 'nm_city' => 'KOTA BANDA ACEH'],
			['id' => 1172, 'province_id' => 1, 'nm_city' => 'KOTA SABANG'],
			['id' => 1173, 'province_id' => 1, 'nm_city' => 'KOTA LANGSA'],
			['id' => 1174, 'province_id' => 1, 'nm_city' => 'KOTA LHOKSEUMAWE'],
			['id' => 1175, 'province_id' => 1, 'nm_city' => 'KOTA SUBULUSSALAM'],
			['id' => 1201, 'province_id' => 2, 'nm_city' => 'KABUPATEN NIAS'],
			['id' => 1202, 'province_id' => 2, 'nm_city' => 'KABUPATEN MANDAILING NATAL'],
			['id' => 1203, 'province_id' => 2, 'nm_city' => 'KABUPATEN TAPANULI SELATAN'],
			['id' => 1204, 'province_id' => 2, 'nm_city' => 'KABUPATEN TAPANULI TENGAH'],
			['id' => 1205, 'province_id' => 2, 'nm_city' => 'KABUPATEN TAPANULI UTARA'],
			['id' => 1206, 'province_id' => 2, 'nm_city' => 'KABUPATEN TOBA SAMOSIR'],
			['id' => 1207, 'province_id' => 2, 'nm_city' => 'KABUPATEN LABUHAN BATU'],
			['id' => 1208, 'province_id' => 2, 'nm_city' => 'KABUPATEN ASAHAN'],
			['id' => 1209, 'province_id' => 2, 'nm_city' => 'KABUPATEN SIMALUNGUN'],
			['id' => 1210, 'province_id' => 2, 'nm_city' => 'KABUPATEN DAIRI'],
			['id' => 1211, 'province_id' => 2, 'nm_city' => 'KABUPATEN KARO'],
			['id' => 1212, 'province_id' => 2, 'nm_city' => 'KABUPATEN DELI SERDANG'],
			['id' => 1213, 'province_id' => 2, 'nm_city' => 'KABUPATEN LANGKAT'],
			['id' => 1214, 'province_id' => 2, 'nm_city' => 'KABUPATEN NIAS SELATAN'],
			['id' => 1215, 'province_id' => 2, 'nm_city' => 'KABUPATEN HUMBANG HASUNDUTAN'],
			['id' => 1216, 'province_id' => 2, 'nm_city' => 'KABUPATEN PAKPAK BHARAT'],
			['id' => 1217, 'province_id' => 2, 'nm_city' => 'KABUPATEN SAMOSIR'],
			['id' => 1218, 'province_id' => 2, 'nm_city' => 'KABUPATEN SERDANG BEDAGAI'],
			['id' => 1219, 'province_id' => 2, 'nm_city' => 'KABUPATEN BATU BARA'],
			['id' => 1220, 'province_id' => 2, 'nm_city' => 'KABUPATEN PADANG LAWAS UTARA'],
			['id' => 1221, 'province_id' => 2, 'nm_city' => 'KABUPATEN PADANG LAWAS'],
			['id' => 1222, 'province_id' => 2, 'nm_city' => 'KABUPATEN LABUHAN BATU SELATAN'],
			['id' => 1223, 'province_id' => 2, 'nm_city' => 'KABUPATEN LABUHAN BATU UTARA'],
			['id' => 1224, 'province_id' => 2, 'nm_city' => 'KABUPATEN NIAS UTARA'],
			['id' => 1225, 'province_id' => 2, 'nm_city' => 'KABUPATEN NIAS BARAT'],
			['id' => 1271, 'province_id' => 2, 'nm_city' => 'KOTA SIBOLGA'],
			['id' => 1272, 'province_id' => 2, 'nm_city' => 'KOTA TANJUNG BALAI'],


			['id' => 1273, 'province_id' => 2, 'nm_city' => 'KOTA PEMATANG SIANTAR'],
			['id' => 1274, 'province_id' => 2, 'nm_city' => 'KOTA TEBING TINGGI'],
			['id' => 1275, 'province_id' => 2, 'nm_city' => 'KOTA MEDAN'],
			['id' => 1276, 'province_id' => 2, 'nm_city' => 'KOTA BINJAI'],
			['id' => 1277, 'province_id' => 2, 'nm_city' => 'KOTA PADANGSIDIMPUAN'],
			['id' => 1278, 'province_id' => 2, 'nm_city' => 'KOTA GUNUNGSITOLI'],
			['id' => 1301, 'province_id' => 3, 'nm_city' => 'KABUPATEN KEPULAUAN MENTAWAI'],
			['id' => 1302, 'province_id' => 3, 'nm_city' => 'KABUPATEN PESISIR SELATAN'],
			['id' => 1303, 'province_id' => 3, 'nm_city' => 'KABUPATEN SOLOK'],
			['id' => 1304, 'province_id' => 3, 'nm_city' => 'KABUPATEN SIJUNJUNG'],
			['id' => 1305, 'province_id' => 3, 'nm_city' => 'KABUPATEN TANAH DATAR'],
			['id' => 1306, 'province_id' => 3, 'nm_city' => 'KABUPATEN PADANG PARIAMAN'],
			['id' => 1307, 'province_id' => 3, 'nm_city' => 'KABUPATEN AGAM'],
			['id' => 1308, 'province_id' => 3, 'nm_city' => 'KABUPATEN LIMA PULUH KOTA'],
			['id' => 1309, 'province_id' => 3, 'nm_city' => 'KABUPATEN PASAMAN'],
			['id' => 1310, 'province_id' => 3, 'nm_city' => 'KABUPATEN SOLOK SELATAN'],
			['id' => 1311, 'province_id' => 3, 'nm_city' => 'KABUPATEN DHARMASRAYA'],
			['id' => 1312, 'province_id' => 3, 'nm_city' => 'KABUPATEN PASAMAN BARAT'],
			['id' => 1371, 'province_id' => 3, 'nm_city' => 'KOTA PADANG'],
			['id' => 1372, 'province_id' => 3, 'nm_city' => 'KOTA SOLOK'],
			['id' => 1373, 'province_id' => 3, 'nm_city' => 'KOTA SAWAH LUNTO'],
			['id' => 1374, 'province_id' => 3, 'nm_city' => 'KOTA PADANG PANJANG'],
			['id' => 1375, 'province_id' => 3, 'nm_city' => 'KOTA BUKITTINGGI'],
			['id' => 1376, 'province_id' => 3, 'nm_city' => 'KOTA PAYAKUMBUH'],
			['id' => 1377, 'province_id' => 3, 'nm_city' => 'KOTA PARIAMAN'],
			['id' => 1401, 'province_id' => 4, 'nm_city' => 'KABUPATEN KUANTAN SINGINGI'],
			['id' => 1402, 'province_id' => 4, 'nm_city' => 'KABUPATEN INDRAGIRI HULU'],
			['id' => 1403, 'province_id' => 4, 'nm_city' => 'KABUPATEN INDRAGIRI HILIR'],
			['id' => 1404, 'province_id' => 4, 'nm_city' => 'KABUPATEN PELALAWAN'],
			['id' => 1405, 'province_id' => 4, 'nm_city' => 'KABUPATEN S I A K'],
			['id' => 1406, 'province_id' => 4, 'nm_city' => 'KABUPATEN KAMPAR'],
			['id' => 1407, 'province_id' => 4, 'nm_city' => 'KABUPATEN ROKAN HULU'],
			['id' => 1408, 'province_id' => 4, 'nm_city' => 'KABUPATEN BENGKALIS'],
			['id' => 1409, 'province_id' => 4, 'nm_city' => 'KABUPATEN ROKAN HILIR'],
			['id' => 1410, 'province_id' => 4, 'nm_city' => 'KABUPATEN KEPULAUAN MERANTI'],
			['id' => 1471, 'province_id' => 4, 'nm_city' => 'KOTA PEKANBARU'],
			['id' => 1473, 'province_id' => 4, 'nm_city' => 'KOTA D U M A I'],
			['id' => 1501, 'province_id' => 5, 'nm_city' => 'KABUPATEN KERINCI'],
			['id' => 1502, 'province_id' => 5, 'nm_city' => 'KABUPATEN MERANGIN'],
			['id' => 1503, 'province_id' => 5, 'nm_city' => 'KABUPATEN SAROLANGUN'],
			['id' => 1504, 'province_id' => 5, 'nm_city' => 'KABUPATEN BATANG HARI'],
			['id' => 1505, 'province_id' => 5, 'nm_city' => 'KABUPATEN MUARO JAMBI'],
			['id' => 1506, 'province_id' => 5, 'nm_city' => 'KABUPATEN TANJUNG JABUNG TIMUR'],
			['id' => 1507, 'province_id' => 5, 'nm_city' => 'KABUPATEN TANJUNG JABUNG BARAT'],
			['id' => 1508, 'province_id' => 5, 'nm_city' => 'KABUPATEN TEBO'],
			['id' => 1509, 'province_id' => 5, 'nm_city' => 'KABUPATEN BUNGO'],
			['id' => 1571, 'province_id' => 5, 'nm_city' => 'KOTA JAMBI'],
			['id' => 1572, 'province_id' => 5, 'nm_city' => 'KOTA SUNGAI PENUH'],
			['id' => 1601, 'province_id' => 6, 'nm_city' => 'KABUPATEN OGAN KOMERING ULU'],
			['id' => 1602, 'province_id' => 6, 'nm_city' => 'KABUPATEN OGAN KOMERING ILIR'],


			['id' => 1603, 'province_id' => 6, 'nm_city' => 'KABUPATEN MUARA ENIM'],
			['id' => 1604, 'province_id' => 6, 'nm_city' => 'KABUPATEN LAHAT'],
			['id' => 1605, 'province_id' => 6, 'nm_city' => 'KABUPATEN MUSI RAWAS'],
			['id' => 1606, 'province_id' => 6, 'nm_city' => 'KABUPATEN MUSI BANYUASIN'],
			['id' => 1607, 'province_id' => 6, 'nm_city' => 'KABUPATEN BANYU ASIN'],
			['id' => 1608, 'province_id' => 6, 'nm_city' => 'KABUPATEN OGAN KOMERING ULU SELATAN'],
			['id' => 1609, 'province_id' => 6, 'nm_city' => 'KABUPATEN OGAN KOMERING ULU TIMUR'],
			['id' => 1610, 'province_id' => 6, 'nm_city' => 'KABUPATEN OGAN ILIR'],
			['id' => 1611, 'province_id' => 6, 'nm_city' => 'KABUPATEN EMPAT LAWANG'],
			['id' => 1612, 'province_id' => 6, 'nm_city' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'],
			['id' => 1613, 'province_id' => 6, 'nm_city' => 'KABUPATEN MUSI RAWAS UTARA'],
			['id' => 1671, 'province_id' => 6, 'nm_city' => 'KOTA PALEMBANG'],
			['id' => 1672, 'province_id' => 6, 'nm_city' => 'KOTA PRABUMULIH'],
			['id' => 1673, 'province_id' => 6, 'nm_city' => 'KOTA PAGAR ALAM'],
			['id' => 1674, 'province_id' => 6, 'nm_city' => 'KOTA LUBUKLINGGAU'],
			['id' => 1701, 'province_id' => 7, 'nm_city' => 'KABUPATEN BENGKULU SELATAN'],
			['id' => 1702, 'province_id' => 7, 'nm_city' => 'KABUPATEN REJANG LEBONG'],
			['id' => 1703, 'province_id' => 7, 'nm_city' => 'KABUPATEN BENGKULU UTARA'],
			['id' => 1704, 'province_id' => 7, 'nm_city' => 'KABUPATEN KAUR'],
			['id' => 1705, 'province_id' => 7, 'nm_city' => 'KABUPATEN SELUMA'],
			['id' => 1706, 'province_id' => 7, 'nm_city' => 'KABUPATEN MUKOMUKO'],
			['id' => 1707, 'province_id' => 7, 'nm_city' => 'KABUPATEN LEBONG'],
			['id' => 1708, 'province_id' => 7, 'nm_city' => 'KABUPATEN KEPAHIANG'],
			['id' => 1709, 'province_id' => 7, 'nm_city' => 'KABUPATEN BENGKULU TENGAH'],
			['id' => 1771, 'province_id' => 7, 'nm_city' => 'KOTA BENGKULU'],
			['id' => 1801, 'province_id' => 8, 'nm_city' => 'KABUPATEN LAMPUNG BARAT'],
			['id' => 1802, 'province_id' => 8, 'nm_city' => 'KABUPATEN TANGGAMUS'],
			['id' => 1803, 'province_id' => 8, 'nm_city' => 'KABUPATEN LAMPUNG SELATAN'],
			['id' => 1804, 'province_id' => 8, 'nm_city' => 'KABUPATEN LAMPUNG TIMUR'],
			['id' => 1805, 'province_id' => 8, 'nm_city' => 'KABUPATEN LAMPUNG TENGAH'],
			['id' => 1806, 'province_id' => 8, 'nm_city' => 'KABUPATEN LAMPUNG UTARA'],
			['id' => 1807, 'province_id' => 8, 'nm_city' => 'KABUPATEN WAY KANAN'],
			['id' => 1808, 'province_id' => 8, 'nm_city' => 'KABUPATEN TULANGBAWANG'],
			['id' => 1809, 'province_id' => 8, 'nm_city' => 'KABUPATEN PESAWARAN'],
			['id' => 1810, 'province_id' => 8, 'nm_city' => 'KABUPATEN PRINGSEWU'],
			['id' => 1811, 'province_id' => 8, 'nm_city' => 'KABUPATEN MESUJI'],
			['id' => 1812, 'province_id' => 8, 'nm_city' => 'KABUPATEN TULANG BAWANG BARAT'],
			['id' => 1813, 'province_id' => 8, 'nm_city' => 'KABUPATEN PESISIR BARAT'],
			['id' => 1871, 'province_id' => 8, 'nm_city' => 'KOTA BANDAR LAMPUNG'],
			['id' => 1872, 'province_id' => 8, 'nm_city' => 'KOTA METRO'],
			['id' => 1901, 'province_id' => 9, 'nm_city' => 'KABUPATEN BANGKA'],
			['id' => 1902, 'province_id' => 9, 'nm_city' => 'KABUPATEN BELITUNG'],
			['id' => 1903, 'province_id' => 9, 'nm_city' => 'KABUPATEN BANGKA BARAT'],
			['id' => 1904, 'province_id' => 9, 'nm_city' => 'KABUPATEN BANGKA TENGAH'],
			['id' => 1905, 'province_id' => 9, 'nm_city' => 'KABUPATEN BANGKA SELATAN'],
			['id' => 1906, 'province_id' => 9, 'nm_city' => 'KABUPATEN BELITUNG TIMUR'],
			['id' => 1971, 'province_id' => 9, 'nm_city' => 'KOTA PANGKAL PINANG'],
			['id' => 2101, 'province_id' => 10, 'nm_city' => 'KABUPATEN KARIMUN'],
			['id' => 2102, 'province_id' => 10, 'nm_city' => 'KABUPATEN BINTAN'],
			['id' => 2103, 'province_id' => 10, 'nm_city' => 'KABUPATEN NATUNA'],


			['id' => 2104, 'province_id' => 10, 'nm_city' => 'KABUPATEN LINGGA'],
			['id' => 2105, 'province_id' => 10, 'nm_city' => 'KABUPATEN KEPULAUAN ANAMBAS'],
			['id' => 2171, 'province_id' => 10, 'nm_city' => 'KOTA B A T A M'],
			['id' => 2172, 'province_id' => 10, 'nm_city' => 'KOTA TANJUNG PINANG'],
			['id' => 3101, 'province_id' => 11, 'nm_city' => 'KABUPATEN KEPULAUAN SERIBU'],
			['id' => 3171, 'province_id' => 11, 'nm_city' => 'KOTA JAKARTA SELATAN'],
			['id' => 3172, 'province_id' => 11, 'nm_city' => 'KOTA JAKARTA TIMUR'],
			['id' => 3173, 'province_id' => 11, 'nm_city' => 'KOTA JAKARTA PUSAT'],
			['id' => 3174, 'province_id' => 11, 'nm_city' => 'KOTA JAKARTA BARAT'],
			['id' => 3175, 'province_id' => 11, 'nm_city' => 'KOTA JAKARTA UTARA'],
			['id' => 3201, 'province_id' => 12, 'nm_city' => 'KABUPATEN BOGOR'],
			['id' => 3202, 'province_id' => 12, 'nm_city' => 'KABUPATEN SUKABUMI'],
			['id' => 3203, 'province_id' => 12, 'nm_city' => 'KABUPATEN CIANJUR'],
			['id' => 3204, 'province_id' => 12, 'nm_city' => 'KABUPATEN BANDUNG'],
			['id' => 3205, 'province_id' => 12, 'nm_city' => 'KABUPATEN GARUT'],
			['id' => 3206, 'province_id' => 12, 'nm_city' => 'KABUPATEN TASIKMALAYA'],
			['id' => 3207, 'province_id' => 12, 'nm_city' => 'KABUPATEN CIAMIS'],
			['id' => 3208, 'province_id' => 12, 'nm_city' => 'KABUPATEN KUNINGAN'],
			['id' => 3209, 'province_id' => 12, 'nm_city' => 'KABUPATEN CIREBON'],
			['id' => 3210, 'province_id' => 12, 'nm_city' => 'KABUPATEN MAJALENGKA'],
			['id' => 3211, 'province_id' => 12, 'nm_city' => 'KABUPATEN SUMEDANG'],
			['id' => 3212, 'province_id' => 12, 'nm_city' => 'KABUPATEN INDRAMAYU'],
			['id' => 3213, 'province_id' => 12, 'nm_city' => 'KABUPATEN SUBANG'],
			['id' => 3214, 'province_id' => 12, 'nm_city' => 'KABUPATEN PURWAKARTA'],
			['id' => 3215, 'province_id' => 12, 'nm_city' => 'KABUPATEN KARAWANG'],
			['id' => 3216, 'province_id' => 12, 'nm_city' => 'KABUPATEN BEKASI'],
			['id' => 3217, 'province_id' => 12, 'nm_city' => 'KABUPATEN BANDUNG BARAT'],
			['id' => 3218, 'province_id' => 12, 'nm_city' => 'KABUPATEN PANGANDARAN'],
			['id' => 3271, 'province_id' => 12, 'nm_city' => 'KOTA BOGOR'],
			['id' => 3272, 'province_id' => 12, 'nm_city' => 'KOTA SUKABUMI'],
			['id' => 3273, 'province_id' => 12, 'nm_city' => 'KOTA BANDUNG'],
			['id' => 3274, 'province_id' => 12, 'nm_city' => 'KOTA CIREBON'],
			['id' => 3275, 'province_id' => 12, 'nm_city' => 'KOTA BEKASI'],
			['id' => 3276, 'province_id' => 12, 'nm_city' => 'KOTA DEPOK'],
			['id' => 3277, 'province_id' => 12, 'nm_city' => 'KOTA CIMAHI'],
			['id' => 3278, 'province_id' => 12, 'nm_city' => 'KOTA TASIKMALAYA'],
			['id' => 3279, 'province_id' => 12, 'nm_city' => 'KOTA BANJAR'],
			['id' => 3301, 'province_id' => 13, 'nm_city' => 'KABUPATEN CILACAP'],
			['id' => 3302, 'province_id' => 13, 'nm_city' => 'KABUPATEN BANYUMAS'],
			['id' => 3303, 'province_id' => 13, 'nm_city' => 'KABUPATEN PURBALINGGA'],
			['id' => 3304, 'province_id' => 13, 'nm_city' => 'KABUPATEN BANJARNEGARA'],
			['id' => 3305, 'province_id' => 13, 'nm_city' => 'KABUPATEN KEBUMEN'],
			['id' => 3306, 'province_id' => 13, 'nm_city' => 'KABUPATEN PURWOREJO'],
			['id' => 3307, 'province_id' => 13, 'nm_city' => 'KABUPATEN WONOSOBO'],
			['id' => 3308, 'province_id' => 13, 'nm_city' => 'KABUPATEN MAGELANG'],
			['id' => 3309, 'province_id' => 13, 'nm_city' => 'KABUPATEN BOYOLALI'],
			['id' => 3310, 'province_id' => 13, 'nm_city' => 'KABUPATEN KLATEN'],
			['id' => 3311, 'province_id' => 13, 'nm_city' => 'KABUPATEN SUKOHARJO'],
			['id' => 3312, 'province_id' => 13, 'nm_city' => 'KABUPATEN WONOGIRI'],
			['id' => 3313, 'province_id' => 13, 'nm_city' => 'KABUPATEN KARANGANYAR'],


			['id' => 3314, 'province_id' => 13, 'nm_city' => 'KABUPATEN SRAGEN'],
			['id' => 3315, 'province_id' => 13, 'nm_city' => 'KABUPATEN GROBOGAN'],
			['id' => 3316, 'province_id' => 13, 'nm_city' => 'KABUPATEN BLORA'],
			['id' => 3317, 'province_id' => 13, 'nm_city' => 'KABUPATEN REMBANG'],
			['id' => 3318, 'province_id' => 13, 'nm_city' => 'KABUPATEN PATI'],
			['id' => 3319, 'province_id' => 13, 'nm_city' => 'KABUPATEN KUDUS'],
			['id' => 3320, 'province_id' => 13, 'nm_city' => 'KABUPATEN JEPARA'],
			['id' => 3321, 'province_id' => 13, 'nm_city' => 'KABUPATEN DEMAK'],
			['id' => 3322, 'province_id' => 13, 'nm_city' => 'KABUPATEN SEMARANG'],
			['id' => 3323, 'province_id' => 13, 'nm_city' => 'KABUPATEN TEMANGGUNG'],
			['id' => 3324, 'province_id' => 13, 'nm_city' => 'KABUPATEN KENDAL'],
			['id' => 3325, 'province_id' => 13, 'nm_city' => 'KABUPATEN BATANG'],
			['id' => 3326, 'province_id' => 13, 'nm_city' => 'KABUPATEN PEKALONGAN'],
			['id' => 3327, 'province_id' => 13, 'nm_city' => 'KABUPATEN PEMALANG'],
			['id' => 3328, 'province_id' => 13, 'nm_city' => 'KABUPATEN TEGAL'],
			['id' => 3329, 'province_id' => 13, 'nm_city' => 'KABUPATEN BREBES'],
			['id' => 3371, 'province_id' => 13, 'nm_city' => 'KOTA MAGELANG'],
			['id' => 3372, 'province_id' => 13, 'nm_city' => 'KOTA SURAKARTA'],
			['id' => 3373, 'province_id' => 13, 'nm_city' => 'KOTA SALATIGA'],
			['id' => 3374, 'province_id' => 13, 'nm_city' => 'KOTA SEMARANG'],
			['id' => 3375, 'province_id' => 13, 'nm_city' => 'KOTA PEKALONGAN'],
			['id' => 3376, 'province_id' => 13, 'nm_city' => 'KOTA TEGAL'],
			['id' => 3401, 'province_id' => 14, 'nm_city' => 'KABUPATEN KULON PROGO'],
			['id' => 3402, 'province_id' => 14, 'nm_city' => 'KABUPATEN BANTUL'],
			['id' => 3403, 'province_id' => 14, 'nm_city' => 'KABUPATEN GUNUNG KIDUL'],
			['id' => 3404, 'province_id' => 14, 'nm_city' => 'KABUPATEN SLEMAN'],
			['id' => 3471, 'province_id' => 14, 'nm_city' => 'KOTA YOGYAKARTA'],
			['id' => 3501, 'province_id' => 15, 'nm_city' => 'KABUPATEN PACITAN'],
			['id' => 3502, 'province_id' => 15, 'nm_city' => 'KABUPATEN PONOROGO'],
			['id' => 3503, 'province_id' => 15, 'nm_city' => 'KABUPATEN TRENGGALEK'],
			['id' => 3504, 'province_id' => 15, 'nm_city' => 'KABUPATEN TULUNGAGUNG'],
			['id' => 3505, 'province_id' => 15, 'nm_city' => 'KABUPATEN BLITAR'],
			['id' => 3506, 'province_id' => 15, 'nm_city' => 'KABUPATEN KEDIRI'],
			['id' => 3507, 'province_id' => 15, 'nm_city' => 'KABUPATEN MALANG'],
			['id' => 3508, 'province_id' => 15, 'nm_city' => 'KABUPATEN LUMAJANG'],
			['id' => 3509, 'province_id' => 15, 'nm_city' => 'KABUPATEN JEMBER'],
			['id' => 3510, 'province_id' => 15, 'nm_city' => 'KABUPATEN BANYUWANGI'],
			['id' => 3511, 'province_id' => 15, 'nm_city' => 'KABUPATEN BONDOWOSO'],
			['id' => 3512, 'province_id' => 15, 'nm_city' => 'KABUPATEN SITUBONDO'],
			['id' => 3513, 'province_id' => 15, 'nm_city' => 'KABUPATEN PROBOLINGGO'],
			['id' => 3514, 'province_id' => 15, 'nm_city' => 'KABUPATEN PASURUAN'],
			['id' => 3515, 'province_id' => 15, 'nm_city' => 'KABUPATEN SIDOARJO'],
			['id' => 3516, 'province_id' => 15, 'nm_city' => 'KABUPATEN MOJOKERTO'],
			['id' => 3517, 'province_id' => 15, 'nm_city' => 'KABUPATEN JOMBANG'],
			['id' => 3518, 'province_id' => 15, 'nm_city' => 'KABUPATEN NGANJUK'],
			['id' => 3519, 'province_id' => 15, 'nm_city' => 'KABUPATEN MADIUN'],
			['id' => 3520, 'province_id' => 15, 'nm_city' => 'KABUPATEN MAGETAN'],
			['id' => 3521, 'province_id' => 15, 'nm_city' => 'KABUPATEN NGAWI'],
			['id' => 3522, 'province_id' => 15, 'nm_city' => 'KABUPATEN BOJONEGORO'],
			['id' => 3523, 'province_id' => 15, 'nm_city' => 'KABUPATEN TUBAN'],


			['id' => 3524, 'province_id' => 15, 'nm_city' => 'KABUPATEN LAMONGAN'],
			['id' => 3525, 'province_id' => 15, 'nm_city' => 'KABUPATEN GRESIK'],
			['id' => 3526, 'province_id' => 15, 'nm_city' => 'KABUPATEN BANGKALAN'],
			['id' => 3527, 'province_id' => 15, 'nm_city' => 'KABUPATEN SAMPANG'],
			['id' => 3528, 'province_id' => 15, 'nm_city' => 'KABUPATEN PAMEKASAN'],
			['id' => 3529, 'province_id' => 15, 'nm_city' => 'KABUPATEN SUMENEP'],
			['id' => 3571, 'province_id' => 15, 'nm_city' => 'KOTA KEDIRI'],
			['id' => 3572, 'province_id' => 15, 'nm_city' => 'KOTA BLITAR'],
			['id' => 3573, 'province_id' => 15, 'nm_city' => 'KOTA MALANG'],
			['id' => 3574, 'province_id' => 15, 'nm_city' => 'KOTA PROBOLINGGO'],
			['id' => 3575, 'province_id' => 15, 'nm_city' => 'KOTA PASURUAN'],
			['id' => 3576, 'province_id' => 15, 'nm_city' => 'KOTA MOJOKERTO'],
			['id' => 3577, 'province_id' => 15, 'nm_city' => 'KOTA MADIUN'],
			['id' => 3578, 'province_id' => 15, 'nm_city' => 'KOTA SURABAYA'],
			['id' => 3579, 'province_id' => 15, 'nm_city' => 'KOTA BATU'],
			['id' => 3601, 'province_id' => 16, 'nm_city' => 'KABUPATEN PANDEGLANG'],
			['id' => 3602, 'province_id' => 16, 'nm_city' => 'KABUPATEN LEBAK'],
			['id' => 3603, 'province_id' => 16, 'nm_city' => 'KABUPATEN TANGERANG'],
			['id' => 3604, 'province_id' => 16, 'nm_city' => 'KABUPATEN SERANG'],
			['id' => 3671, 'province_id' => 16, 'nm_city' => 'KOTA TANGERANG'],
			['id' => 3672, 'province_id' => 16, 'nm_city' => 'KOTA CILEGON'],
			['id' => 3673, 'province_id' => 16, 'nm_city' => 'KOTA SERANG'],
			['id' => 3674, 'province_id' => 16, 'nm_city' => 'KOTA TANGERANG SELATAN'],
			['id' => 5101, 'province_id' => 17, 'nm_city' => 'KABUPATEN JEMBRANA'],
			['id' => 5102, 'province_id' => 17, 'nm_city' => 'KABUPATEN TABANAN'],
			['id' => 5103, 'province_id' => 17, 'nm_city' => 'KABUPATEN BADUNG'],
			['id' => 5104, 'province_id' => 17, 'nm_city' => 'KABUPATEN GIANYAR'],
			['id' => 5105, 'province_id' => 17, 'nm_city' => 'KABUPATEN KLUNGKUNG'],
			['id' => 5106, 'province_id' => 17, 'nm_city' => 'KABUPATEN BANGLI'],
			['id' => 5107, 'province_id' => 17, 'nm_city' => 'KABUPATEN KARANG ASEM'],
			['id' => 5108, 'province_id' => 17, 'nm_city' => 'KABUPATEN BULELENG'],
			['id' => 5171, 'province_id' => 17, 'nm_city' => 'KOTA DENPASAR'],
			['id' => 5201, 'province_id' => 18, 'nm_city' => 'KABUPATEN LOMBOK BARAT'],
			['id' => 5202, 'province_id' => 18, 'nm_city' => 'KABUPATEN LOMBOK TENGAH'],
			['id' => 5203, 'province_id' => 18, 'nm_city' => 'KABUPATEN LOMBOK TIMUR'],
			['id' => 5204, 'province_id' => 18, 'nm_city' => 'KABUPATEN SUMBAWA'],
			['id' => 5205, 'province_id' => 18, 'nm_city' => 'KABUPATEN DOMPU'],
			['id' => 5206, 'province_id' => 18, 'nm_city' => 'KABUPATEN BIMA'],
			['id' => 5207, 'province_id' => 18, 'nm_city' => 'KABUPATEN SUMBAWA BARAT'],
			['id' => 5208, 'province_id' => 18, 'nm_city' => 'KABUPATEN LOMBOK UTARA'],
			['id' => 5271, 'province_id' => 18, 'nm_city' => 'KOTA MATARAM'],
			['id' => 5272, 'province_id' => 18, 'nm_city' => 'KOTA BIMA'],
			['id' => 5301, 'province_id' => 19, 'nm_city' => 'KABUPATEN SUMBA BARAT'],
			['id' => 5302, 'province_id' => 19, 'nm_city' => 'KABUPATEN SUMBA TIMUR'],
			['id' => 5303, 'province_id' => 19, 'nm_city' => 'KABUPATEN KUPANG'],
			['id' => 5304, 'province_id' => 19, 'nm_city' => 'KABUPATEN TIMOR TENGAH SELATAN'],
			['id' => 5305, 'province_id' => 19, 'nm_city' => 'KABUPATEN TIMOR TENGAH UTARA'],
			['id' => 5306, 'province_id' => 19, 'nm_city' => 'KABUPATEN BELU'],
			['id' => 5307, 'province_id' => 19, 'nm_city' => 'KABUPATEN ALOR'],
			['id' => 5308, 'province_id' => 19, 'nm_city' => 'KABUPATEN LEMBATA'],


			['id' => 5309, 'province_id' => 19, 'nm_city' => 'KABUPATEN FLORES TIMUR'],
			['id' => 5310, 'province_id' => 19, 'nm_city' => 'KABUPATEN SIKKA'],
			['id' => 5311, 'province_id' => 19, 'nm_city' => 'KABUPATEN ENDE'],
			['id' => 5312, 'province_id' => 19, 'nm_city' => 'KABUPATEN NGADA'],
			['id' => 5313, 'province_id' => 19, 'nm_city' => 'KABUPATEN MANGGARAI'],
			['id' => 5314, 'province_id' => 19, 'nm_city' => 'KABUPATEN ROTE NDAO'],
			['id' => 5315, 'province_id' => 19, 'nm_city' => 'KABUPATEN MANGGARAI BARAT'],
			['id' => 5316, 'province_id' => 19, 'nm_city' => 'KABUPATEN SUMBA TENGAH'],
			['id' => 5317, 'province_id' => 19, 'nm_city' => 'KABUPATEN SUMBA BARAT DAYA'],
			['id' => 5318, 'province_id' => 19, 'nm_city' => 'KABUPATEN NAGEKEO'],
			['id' => 5319, 'province_id' => 19, 'nm_city' => 'KABUPATEN MANGGARAI TIMUR'],
			['id' => 5320, 'province_id' => 19, 'nm_city' => 'KABUPATEN SABU RAIJUA'],
			['id' => 5321, 'province_id' => 19, 'nm_city' => 'KABUPATEN MALAKA'],
			['id' => 5371, 'province_id' => 19, 'nm_city' => 'KOTA KUPANG'],
			['id' => 6101, 'province_id' => 20, 'nm_city' => 'KABUPATEN SAMBAS'],
			['id' => 6102, 'province_id' => 20, 'nm_city' => 'KABUPATEN BENGKAYANG'],
			['id' => 6103, 'province_id' => 20, 'nm_city' => 'KABUPATEN LANDAK'],
			['id' => 6104, 'province_id' => 20, 'nm_city' => 'KABUPATEN MEMPAWAH'],
			['id' => 6105, 'province_id' => 20, 'nm_city' => 'KABUPATEN SANGGAU'],
			['id' => 6106, 'province_id' => 20, 'nm_city' => 'KABUPATEN KETAPANG'],
			['id' => 6107, 'province_id' => 20, 'nm_city' => 'KABUPATEN SINTANG'],
			['id' => 6108, 'province_id' => 20, 'nm_city' => 'KABUPATEN KAPUAS HULU'],
			['id' => 6109, 'province_id' => 20, 'nm_city' => 'KABUPATEN SEKADAU'],
			['id' => 6110, 'province_id' => 20, 'nm_city' => 'KABUPATEN MELAWI'],
			['id' => 6111, 'province_id' => 20, 'nm_city' => 'KABUPATEN KAYONG UTARA'],
			['id' => 6112, 'province_id' => 20, 'nm_city' => 'KABUPATEN KUBU RAYA'],
			['id' => 6171, 'province_id' => 20, 'nm_city' => 'KOTA PONTIANAK'],
			['id' => 6172, 'province_id' => 20, 'nm_city' => 'KOTA SINGKAWANG'],
			['id' => 6201, 'province_id' => 21, 'nm_city' => 'KABUPATEN KOTAWARINGIN BARAT'],
			['id' => 6202, 'province_id' => 21, 'nm_city' => 'KABUPATEN KOTAWARINGIN TIMUR'],
			['id' => 6203, 'province_id' => 21, 'nm_city' => 'KABUPATEN KAPUAS'],
			['id' => 6204, 'province_id' => 21, 'nm_city' => 'KABUPATEN BARITO SELATAN'],
			['id' => 6205, 'province_id' => 21, 'nm_city' => 'KABUPATEN BARITO UTARA'],
			['id' => 6206, 'province_id' => 21, 'nm_city' => 'KABUPATEN SUKAMARA'],
			['id' => 6207, 'province_id' => 21, 'nm_city' => 'KABUPATEN LAMANDAU'],
			['id' => 6208, 'province_id' => 21, 'nm_city' => 'KABUPATEN SERUYAN'],
			['id' => 6209, 'province_id' => 21, 'nm_city' => 'KABUPATEN KATINGAN'],
			['id' => 6210, 'province_id' => 21, 'nm_city' => 'KABUPATEN PULANG PISAU'],
			['id' => 6211, 'province_id' => 21, 'nm_city' => 'KABUPATEN GUNUNG MAS'],
			['id' => 6212, 'province_id' => 21, 'nm_city' => 'KABUPATEN BARITO TIMUR'],
			['id' => 6213, 'province_id' => 21, 'nm_city' => 'KABUPATEN MURUNG RAYA'],
			['id' => 6271, 'province_id' => 21, 'nm_city' => 'KOTA PALANGKA RAYA'],
			['id' => 6301, 'province_id' => 22, 'nm_city' => 'KABUPATEN TANAH LAUT'],
			['id' => 6302, 'province_id' => 22, 'nm_city' => 'KABUPATEN KOTA BARU'],
			['id' => 6303, 'province_id' => 22, 'nm_city' => 'KABUPATEN BANJAR'],
			['id' => 6304, 'province_id' => 22, 'nm_city' => 'KABUPATEN BARITO KUALA'],
			['id' => 6305, 'province_id' => 22, 'nm_city' => 'KABUPATEN TAPIN'],
			['id' => 6306, 'province_id' => 22, 'nm_city' => 'KABUPATEN HULU SUNGAI SELATAN'],
			['id' => 6307, 'province_id' => 22, 'nm_city' => 'KABUPATEN HULU SUNGAI TENGAH'],
			['id' => 6308, 'province_id' => 22, 'nm_city' => 'KABUPATEN HULU SUNGAI UTARA'],


			['id' => 6309, 'province_id' => 22, 'nm_city' => 'KABUPATEN TABALONG'],
			['id' => 6310, 'province_id' => 22, 'nm_city' => 'KABUPATEN TANAH BUMBU'],
			['id' => 6311, 'province_id' => 22, 'nm_city' => 'KABUPATEN BALANGAN'],
			['id' => 6371, 'province_id' => 22, 'nm_city' => 'KOTA BANJARMASIN'],
			['id' => 6372, 'province_id' => 22, 'nm_city' => 'KOTA BANJAR BARU'],
			['id' => 6401, 'province_id' => 23, 'nm_city' => 'KABUPATEN PASER'],
			['id' => 6402, 'province_id' => 23, 'nm_city' => 'KABUPATEN KUTAI BARAT'],
			['id' => 6403, 'province_id' => 23, 'nm_city' => 'KABUPATEN KUTAI KARTANEGARA'],
			['id' => 6404, 'province_id' => 23, 'nm_city' => 'KABUPATEN KUTAI TIMUR'],
			['id' => 6405, 'province_id' => 23, 'nm_city' => 'KABUPATEN BERAU'],
			['id' => 6409, 'province_id' => 23, 'nm_city' => 'KABUPATEN PENAJAM PASER UTARA'],
			['id' => 6411, 'province_id' => 23, 'nm_city' => 'KABUPATEN MAHAKAM HULU'],
			['id' => 6471, 'province_id' => 23, 'nm_city' => 'KOTA BALIKPAPAN'],
			['id' => 6472, 'province_id' => 23, 'nm_city' => 'KOTA SAMARINDA'],
			['id' => 6474, 'province_id' => 23, 'nm_city' => 'KOTA BONTANG'],
			['id' => 6501, 'province_id' => 24, 'nm_city' => 'KABUPATEN MALINAU'],
			['id' => 6502, 'province_id' => 24, 'nm_city' => 'KABUPATEN BULUNGAN'],
			['id' => 6503, 'province_id' => 24, 'nm_city' => 'KABUPATEN TANA TIDUNG'],
			['id' => 6504, 'province_id' => 24, 'nm_city' => 'KABUPATEN NUNUKAN'],
			['id' => 6571, 'province_id' => 24, 'nm_city' => 'KOTA TARAKAN'],
			['id' => 7101, 'province_id' => 25, 'nm_city' => 'KABUPATEN BOLAANG MONGONDOW'],
			['id' => 7102, 'province_id' => 25, 'nm_city' => 'KABUPATEN MINAHASA'],
			['id' => 7103, 'province_id' => 25, 'nm_city' => 'KABUPATEN KEPULAUAN SANGIHE'],
			['id' => 7104, 'province_id' => 25, 'nm_city' => 'KABUPATEN KEPULAUAN TALAUD'],
			['id' => 7105, 'province_id' => 25, 'nm_city' => 'KABUPATEN MINAHASA SELATAN'],
			['id' => 7106, 'province_id' => 25, 'nm_city' => 'KABUPATEN MINAHASA UTARA'],
			['id' => 7107, 'province_id' => 25, 'nm_city' => 'KABUPATEN BOLAANG MONGONDOW UTARA'],
			['id' => 7108, 'province_id' => 25, 'nm_city' => 'KABUPATEN SIAU TAGULANDANG BIARO'],
			['id' => 7109, 'province_id' => 25, 'nm_city' => 'KABUPATEN MINAHASA TENGGARA'],
			['id' => 7110, 'province_id' => 25, 'nm_city' => 'KABUPATEN BOLAANG MONGONDOW SELATAN'],
			['id' => 7111, 'province_id' => 25, 'nm_city' => 'KABUPATEN BOLAANG MONGONDOW TIMUR'],
			['id' => 7171, 'province_id' => 25, 'nm_city' => 'KOTA MANADO'],
			['id' => 7172, 'province_id' => 25, 'nm_city' => 'KOTA BITUNG'],
			['id' => 7173, 'province_id' => 25, 'nm_city' => 'KOTA TOMOHON'],
			['id' => 7174, 'province_id' => 25, 'nm_city' => 'KOTA KOTAMOBAGU'],
			['id' => 7201, 'province_id' => 26, 'nm_city' => 'KABUPATEN BANGGAI KEPULAUAN'],
			['id' => 7202, 'province_id' => 26, 'nm_city' => 'KABUPATEN BANGGAI'],
			['id' => 7203, 'province_id' => 26, 'nm_city' => 'KABUPATEN MOROWALI'],
			['id' => 7204, 'province_id' => 26, 'nm_city' => 'KABUPATEN POSO'],
			['id' => 7205, 'province_id' => 26, 'nm_city' => 'KABUPATEN DONGGALA'],
			['id' => 7206, 'province_id' => 26, 'nm_city' => 'KABUPATEN TOLI-TOLI'],
			['id' => 7207, 'province_id' => 26, 'nm_city' => 'KABUPATEN BUOL'],
			['id' => 7208, 'province_id' => 26, 'nm_city' => 'KABUPATEN PARIGI MOUTONG'],
			['id' => 7209, 'province_id' => 26, 'nm_city' => 'KABUPATEN TOJO UNA-UNA'],
			['id' => 7210, 'province_id' => 26, 'nm_city' => 'KABUPATEN SIGI'],
			['id' => 7211, 'province_id' => 26, 'nm_city' => 'KABUPATEN BANGGAI LAUT'],
			['id' => 7212, 'province_id' => 26, 'nm_city' => 'KABUPATEN MOROWALI UTARA'],
			['id' => 7271, 'province_id' => 26, 'nm_city' => 'KOTA PALU'],
			['id' => 7301, 'province_id' => 27, 'nm_city' => 'KABUPATEN KEPULAUAN SELAYAR'],
			['id' => 7302, 'province_id' => 27, 'nm_city' => 'KABUPATEN BULUKUMBA'],


			['id' => 7303, 'province_id' => 27, 'nm_city' => 'KABUPATEN BANTAENG'],
			['id' => 7304, 'province_id' => 27, 'nm_city' => 'KABUPATEN JENEPONTO'],
			['id' => 7305, 'province_id' => 27, 'nm_city' => 'KABUPATEN TAKALAR'],
			['id' => 7306, 'province_id' => 27, 'nm_city' => 'KABUPATEN GOWA'],
			['id' => 7307, 'province_id' => 27, 'nm_city' => 'KABUPATEN SINJAI'],
			['id' => 7308, 'province_id' => 27, 'nm_city' => 'KABUPATEN MAROS'],
			['id' => 7309, 'province_id' => 27, 'nm_city' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN'],
			['id' => 7310, 'province_id' => 27, 'nm_city' => 'KABUPATEN BARRU'],
			['id' => 7311, 'province_id' => 27, 'nm_city' => 'KABUPATEN BONE'],
			['id' => 7312, 'province_id' => 27, 'nm_city' => 'KABUPATEN SOPPENG'],
			['id' => 7313, 'province_id' => 27, 'nm_city' => 'KABUPATEN WAJO'],
			['id' => 7314, 'province_id' => 27, 'nm_city' => 'KABUPATEN SIDENRENG RAPPANG'],
			['id' => 7315, 'province_id' => 27, 'nm_city' => 'KABUPATEN PINRANG'],
			['id' => 7316, 'province_id' => 27, 'nm_city' => 'KABUPATEN ENREKANG'],
			['id' => 7317, 'province_id' => 27, 'nm_city' => 'KABUPATEN LUWU'],
			['id' => 7318, 'province_id' => 27, 'nm_city' => 'KABUPATEN TANA TORAJA'],
			['id' => 7322, 'province_id' => 27, 'nm_city' => 'KABUPATEN LUWU UTARA'],
			['id' => 7325, 'province_id' => 27, 'nm_city' => 'KABUPATEN LUWU TIMUR'],
			['id' => 7326, 'province_id' => 27, 'nm_city' => 'KABUPATEN TORAJA UTARA'],
			['id' => 7371, 'province_id' => 27, 'nm_city' => 'KOTA MAKASSAR'],
			['id' => 7372, 'province_id' => 27, 'nm_city' => 'KOTA PAREPARE'],
			['id' => 7373, 'province_id' => 27, 'nm_city' => 'KOTA PALOPO'],
			['id' => 7401, 'province_id' => 28, 'nm_city' => 'KABUPATEN BUTON'],
			['id' => 7402, 'province_id' => 28, 'nm_city' => 'KABUPATEN MUNA'],
			['id' => 7403, 'province_id' => 28, 'nm_city' => 'KABUPATEN KONAWE'],
			['id' => 7404, 'province_id' => 28, 'nm_city' => 'KABUPATEN KOLAKA'],
			['id' => 7405, 'province_id' => 28, 'nm_city' => 'KABUPATEN KONAWE SELATAN'],
			['id' => 7406, 'province_id' => 28, 'nm_city' => 'KABUPATEN BOMBANA'],
			['id' => 7407, 'province_id' => 28, 'nm_city' => 'KABUPATEN WAKATOBI'],
			['id' => 7408, 'province_id' => 28, 'nm_city' => 'KABUPATEN KOLAKA UTARA'],
			['id' => 7409, 'province_id' => 28, 'nm_city' => 'KABUPATEN BUTON UTARA'],
			['id' => 7410, 'province_id' => 28, 'nm_city' => 'KABUPATEN KONAWE UTARA'],
			['id' => 7411, 'province_id' => 28, 'nm_city' => 'KABUPATEN KOLAKA TIMUR'],
			['id' => 7412, 'province_id' => 28, 'nm_city' => 'KABUPATEN KONAWE KEPULAUAN'],
			['id' => 7413, 'province_id' => 28, 'nm_city' => 'KABUPATEN MUNA BARAT'],
			['id' => 7414, 'province_id' => 28, 'nm_city' => 'KABUPATEN BUTON TENGAH'],
			['id' => 7415, 'province_id' => 28, 'nm_city' => 'KABUPATEN BUTON SELATAN'],
			['id' => 7471, 'province_id' => 28, 'nm_city' => 'KOTA KENDARI'],
			['id' => 7472, 'province_id' => 28, 'nm_city' => 'KOTA BAUBAU'],
			['id' => 7501, 'province_id' => 29, 'nm_city' => 'KABUPATEN BOALEMO'],
			['id' => 7502, 'province_id' => 29, 'nm_city' => 'KABUPATEN GORONTALO'],
			['id' => 7503, 'province_id' => 29, 'nm_city' => 'KABUPATEN POHUWATO'],
			['id' => 7504, 'province_id' => 29, 'nm_city' => 'KABUPATEN BONE BOLANGO'],
			['id' => 7505, 'province_id' => 29, 'nm_city' => 'KABUPATEN GORONTALO UTARA'],
			['id' => 7571, 'province_id' => 29, 'nm_city' => 'KOTA GORONTALO'],
			['id' => 7601, 'province_id' => 30, 'nm_city' => 'KABUPATEN MAJENE'],
			['id' => 7602, 'province_id' => 30, 'nm_city' => 'KABUPATEN POLEWALI MANDAR'],
			['id' => 7603, 'province_id' => 30, 'nm_city' => 'KABUPATEN MAMASA'],
			['id' => 7604, 'province_id' => 30, 'nm_city' => 'KABUPATEN MAMUJU'],
			['id' => 7605, 'province_id' => 30, 'nm_city' => 'KABUPATEN MAMUJU UTARA'],


			['id' => 7606, 'province_id' => 30, 'nm_city' => 'KABUPATEN MAMUJU TENGAH'],
			['id' => 8101, 'province_id' => 31, 'nm_city' => 'KABUPATEN MALUKU TENGGARA BARAT'],
			['id' => 8102, 'province_id' => 31, 'nm_city' => 'KABUPATEN MALUKU TENGGARA'],
			['id' => 8103, 'province_id' => 31, 'nm_city' => 'KABUPATEN MALUKU TENGAH'],
			['id' => 8104, 'province_id' => 31, 'nm_city' => 'KABUPATEN BURU'],
			['id' => 8105, 'province_id' => 31, 'nm_city' => 'KABUPATEN KEPULAUAN ARU'],
			['id' => 8106, 'province_id' => 31, 'nm_city' => 'KABUPATEN SERAM BAGIAN BARAT'],
			['id' => 8107, 'province_id' => 31, 'nm_city' => 'KABUPATEN SERAM BAGIAN TIMUR'],
			['id' => 8108, 'province_id' => 31, 'nm_city' => 'KABUPATEN MALUKU BARAT DAYA'],
			['id' => 8109, 'province_id' => 31, 'nm_city' => 'KABUPATEN BURU SELATAN'],
			['id' => 8171, 'province_id' => 31, 'nm_city' => 'KOTA AMBON'],
			['id' => 8172, 'province_id' => 31, 'nm_city' => 'KOTA TUAL'],
			['id' => 8201, 'province_id' => 32, 'nm_city' => 'KABUPATEN HALMAHERA BARAT'],
			['id' => 8202, 'province_id' => 32, 'nm_city' => 'KABUPATEN HALMAHERA TENGAH'],
			['id' => 8203, 'province_id' => 32, 'nm_city' => 'KABUPATEN KEPULAUAN SULA'],
			['id' => 8204, 'province_id' => 32, 'nm_city' => 'KABUPATEN HALMAHERA SELATAN'],
			['id' => 8205, 'province_id' => 32, 'nm_city' => 'KABUPATEN HALMAHERA UTARA'],
			['id' => 8206, 'province_id' => 32, 'nm_city' => 'KABUPATEN HALMAHERA TIMUR'],
			['id' => 8207, 'province_id' => 32, 'nm_city' => 'KABUPATEN PULAU MOROTAI'],
			['id' => 8208, 'province_id' => 32, 'nm_city' => 'KABUPATEN PULAU TALIABU'],
			['id' => 8271, 'province_id' => 32, 'nm_city' => 'KOTA TERNATE'],
			['id' => 8272, 'province_id' => 32, 'nm_city' => 'KOTA TIDORE KEPULAUAN'],
			['id' => 9101, 'province_id' => 33, 'nm_city' => 'KABUPATEN FAKFAK'],
			['id' => 9102, 'province_id' => 33, 'nm_city' => 'KABUPATEN KAIMANA'],
			['id' => 9103, 'province_id' => 33, 'nm_city' => 'KABUPATEN TELUK WONDAMA'],
			['id' => 9104, 'province_id' => 33, 'nm_city' => 'KABUPATEN TELUK BINTUNI'],
			['id' => 9105, 'province_id' => 33, 'nm_city' => 'KABUPATEN MANOKWARI'],
			['id' => 9106, 'province_id' => 33, 'nm_city' => 'KABUPATEN SORONG SELATAN'],
			['id' => 9107, 'province_id' => 33, 'nm_city' => 'KABUPATEN SORONG'],
			['id' => 9108, 'province_id' => 33, 'nm_city' => 'KABUPATEN RAJA AMPAT'],
			['id' => 9109, 'province_id' => 33, 'nm_city' => 'KABUPATEN TAMBRAUW'],
			['id' => 9110, 'province_id' => 33, 'nm_city' => 'KABUPATEN MAYBRAT'],
			['id' => 9111, 'province_id' => 33, 'nm_city' => 'KABUPATEN MANOKWARI SELATAN'],
			['id' => 9112, 'province_id' => 33, 'nm_city' => 'KABUPATEN PEGUNUNGAN ARFAK'],
			['id' => 9171, 'province_id' => 33, 'nm_city' => 'KOTA SORONG'],
			['id' => 9401, 'province_id' => 34, 'nm_city' => 'KABUPATEN MERAUKE'],
			['id' => 9402, 'province_id' => 34, 'nm_city' => 'KABUPATEN JAYAWIJAYA'],
			['id' => 9403, 'province_id' => 34, 'nm_city' => 'KABUPATEN JAYAPURA'],
			['id' => 9404, 'province_id' => 34, 'nm_city' => 'KABUPATEN NABIRE'],
			['id' => 9408, 'province_id' => 34, 'nm_city' => 'KABUPATEN KEPULAUAN YAPEN'],
			['id' => 9409, 'province_id' => 34, 'nm_city' => 'KABUPATEN BIAK NUMFOR'],
			['id' => 9410, 'province_id' => 34, 'nm_city' => 'KABUPATEN PANIAI'],
			['id' => 9411, 'province_id' => 34, 'nm_city' => 'KABUPATEN PUNCAK JAYA'],
			['id' => 9412, 'province_id' => 34, 'nm_city' => 'KABUPATEN MIMIKA'],
			['id' => 9413, 'province_id' => 34, 'nm_city' => 'KABUPATEN BOVEN DIGOEL'],
			['id' => 9414, 'province_id' => 34, 'nm_city' => 'KABUPATEN MAPPI'],
			['id' => 9415, 'province_id' => 34, 'nm_city' => 'KABUPATEN ASMAT'],
			['id' => 9416, 'province_id' => 34, 'nm_city' => 'KABUPATEN YAHUKIMO'],
			['id' => 9417, 'province_id' => 34, 'nm_city' => 'KABUPATEN PEGUNUNGAN BINTANG'],
			['id' => 9418, 'province_id' => 34, 'nm_city' => 'KABUPATEN TOLIKARA'],


			['id' => 9419, 'province_id' => 34, 'nm_city' => 'KABUPATEN SARMI'],
			['id' => 9420, 'province_id' => 34, 'nm_city' => 'KABUPATEN KEEROM'],
			['id' => 9426, 'province_id' => 34, 'nm_city' => 'KABUPATEN WAROPEN'],
			['id' => 9427, 'province_id' => 34, 'nm_city' => 'KABUPATEN SUPIORI'],
			['id' => 9428, 'province_id' => 34, 'nm_city' => 'KABUPATEN MAMBERAMO RAYA'],
			['id' => 9429, 'province_id' => 34, 'nm_city' => 'KABUPATEN NDUGA'],
			['id' => 9430, 'province_id' => 34, 'nm_city' => 'KABUPATEN LANNY JAYA'],
			['id' => 9431, 'province_id' => 34, 'nm_city' => 'KABUPATEN MAMBERAMO TENGAH'],
			['id' => 9432, 'province_id' => 34, 'nm_city' => 'KABUPATEN YALIMO'],
			['id' => 9433, 'province_id' => 34, 'nm_city' => 'KABUPATEN PUNCAK'],
			['id' => 9434, 'province_id' => 34, 'nm_city' => 'KABUPATEN DOGIYAI'],
			['id' => 9435, 'province_id' => 34, 'nm_city' => 'KABUPATEN INTAN JAYA'],
			['id' => 9436, 'province_id' => 34, 'nm_city' => 'KABUPATEN DEIYAI'],
			['id' => 9471, 'province_id' => 34, 'nm_city' => 'KOTA JAYAPURA']
		];

        foreach($data as $value) {
	        City::create($value);
	    }

    }
}
