<?php

use Illuminate\Database\Seeder;
use App\Models\CourseContent;

class CourseContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas = [
        	['course_id' => 1, 'title' => 'Jati Diri Koperasi', 'content' => 'Tugas DML1 .docx', 'module' => 'JATIDIRI RIO.pdf', 'video' => '_c7qwb02a7Y'],
			['course_id' => 1, 'title' => 'Organisasi dan Manajemen Koperasi', 'content' => 'Di Pasal 4 UU Nomor 25/1992 menyebut, empat fungsi dan peran koperasi, antara lain:\r\n\r\n1. Membangun dan mengembangkan potensi dan kemampuan ekonomi anggota pada khususnya dan masyarakat pada umumnya untuk meningkatkan kesejahteraan ekonomi dan sosialnya\r\n\r\n2. Berperan serta secara aktif dalam upaya mempertinggi kualitas kehidupan manusia dan masyarakat\r\n\r\n3. Memperkokoh perekonomian rakyat sebagai dasar kekuatan dan ketahanan perekonomian nasional dengan koperasi sebagai sokogurunya\r\n\r\n4. Berusaha untuk mewujudkan dan mengembangkan perekonomian nasional yang merupakan usaha bersama berdasar atas asas kekeluargaan dan demokrasi ekonomi.\r\n\r\nDalam perannya, koperasi kerap memberi bantuan, seperti kredit atau pinjaman dana kepada anggota dalam hal finansial. Pembentukan koperasi diharapkan dapat meningkatkan kesejahteraan sosial masyarakat di Indonesia.', 'module' => '04 Organisasi dan Manajemen Koperasi._compressed.pdf', 'video' => 'rFbqDgOZMqQ'],
			['course_id' => 1, 'title' => 'Anggaran Dasar dan anggaran rumah tangga (ADART)', 'content' => 'Dalam UU Nomor 25/1992, koperasi dapat berbentuk koperasi primer dan sekunder.\r\n\r\n1. Koperasi primer adalah koperasi yang didirikan oleh dan beranggotakan orang-seorang\r\n\r\n2. Koperasi sekunder adalah koperasi yang didirikan oleh dan beranggotakan koperasi.\r\n\r\nJenis koperasi didasarkan pada kesamaan kegiatan dan kepentingan ekonomi anggotanya.\r\n\r\nSementara itu, UU Nomor 17 Tahun 2012 tentang Perkoperasian yang dibatalkan Mahkamah Konstitusi (MK) ada 4 jenis koperasi, yakni koperasi konsumen, koperasi produsem, koperasi jasa, dan koperasi simpan pinjam.\r\n\r\n1. Koperasi konsumen menyelenggarakan kegiatan usaha pelayanan di bidang penyediaan barang kebutuhan anggota dan non-anggota.\r\n\r\n2. Koperasi produsen menyelenggarakan kegiatan usaha pelayanan di bidang pengadaan sarana produksi dan pemasaran produksi yang dihasilkan anggota kepada anggota dan non-anggota.\r\n\r\n3. Koperasi jasa menyelenggarakan kegiatan usaha pelayanan jasa non-simpan pinjam yang diperlukan oleh anggota dan non-anggota.\r\n\r\n4. Koperasi simpan pinjam menjalankan usaha simpan pinjam sebagai satu-satunya usaha yang melayani anggota.\r\n\r\nSayangnya UU No. 17/2012 telah dibatalkan MK karena dianggap bertentangan dengan Undang-undang Dasar (UUD) 1945 dan tidak mempunyai kekuatan hukum mengikat. Oleh karena itu, UU Perkoperasian yang berlaku di Indonesia masih aturan lama, yaitu UU No. 25/1992.', 'module' => 'Slide ADART hotma.pdf', 'video' => '3H9IrPcwfzM'],
			['course_id' => 1, 'title' => 'Rapat Anggota Koperasi', 'content' => 'Dalam Pasal 5 disebutkan, prinsip pelaksanaan koperasi, sebagai berikut:\r\n\r\n1. Keanggotaan bersifat sukarela dan terbuka\r\n\r\n2. Pengelolaan dilakukan secara demokratis\r\n\r\n3. Pembagian Sisa Hasil Usaha (SHU) dilakukan secara adil sebanding dengan besarnya jasa usaha masing-masing anggota\r\n\r\n4. Pemberian balas jasa yang terbatas terhadap modal\r\n\r\n5. Kemandirian\r\n\r\nDalam mengembangkan koperasi, juga wajib menerapkan prinsip:\r\n\r\n1. Pendidikan perkoperasian\r\n\r\n2. Kerja sama antar koperasi.\r\n\r\nKarena siapapun dapat bergabung menjadi anggota koperasi, maka pengelolaan mengedepankan asas demokrasi. Dalam menetapkan keputusan segala hal mengenai koperasi, dilakukan dengan cara musyawarah atau voting suara terbanyak dari para anggotanya.', 'module' => 'RAPAT_ANGGOTA_REV_1.pdf', 'video' => 'ObIcY_eU6t8'],
			['course_id' => 1, 'title' => 'RK-RAPBK', 'content' => 'Koperasi didirikan untuk meningkatkan kesejahteraan para anggotanya. Untuk itu, menjadi anggota sebuah koperasi dapat memberikan banyak keuntungan. Salah satunya untuk menambah penghasilan.\r\n\r\n1. Anggota koperasi berhak mendapatkan SHU. Besar kecilnya SHU yang diterima anggota koperasi berdasarkan atas modal yang ditanam dan keuntungan yang diraih koperasi tersebut.\r\n\r\n2. Jadi anggota koperasi bisa menghemat pengeluaran. Anda dapat membeli barang di koperasi dengan harga lebih murah, karena terdaftar sebagai anggota.\r\n\r\n3. Pinjam uang di koperasi juga lebih untung karena bunga yang dibebankan lebih rendah, sehingga cicilan kredit lebih kecil.\r\n\r\n4. Jadi anggota koperasi juga bisa mendapatkan pelatihan usaha dan memperluas relasi usaha. Dengan begitu, kualitas Anda sebagai seorang individu akan menjadi lebih baik.', 'module' => 'RK-RAPBK_compressed.pdf', 'video' => 'K9Tj9G8ARwA'],
			['course_id' => 1, 'title' => 'Permodalan dan Pembagian Sisa Hasil Usaha (SHU) Koperasi', 'content' => 'Koperasi memegang peranan penting dalam perekonomian Indonesia selama ini. Bahkan sudah terbukti koperasi menjadi penyelamat ekonomi saat krisis moneter tahun 1998 menerjang Indonesia. Kalau taraf hidup masyarakat meningkat karena koperasi, maka ekonomi negara ini juga ikut terdongkrak.\r\n\r\nSaat ini, masyarakat harus waspada terhadap kehadiran koperasi bodong. Jika ingin mendaftar menjadi anggota, pastikan Anda memilih koperasi yang terdaftar resmi di Kementerian Koperasi dan UKM maupun Otoritas Jasa Keuangan (OJK). Jangan sampai uang Anda lenyap karena terjerat kasus penipuan atau penggelapan uang oleh koperasi abal-abal. ', 'module' => 'PERMODALAN KOPERASI.pdf', 'video' => 'T2z4OAw_bpk'],
			['course_id' => 1, 'title' => 'Laporan Keuangan Koperasi', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'LAP KEU KOP_compressed.pdf', 'video' => 'xp15P6iJ6Jc'],
			['course_id' => 2, 'title' => 'Pengantar RAT', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PENGANTAR RAT - TIARA PDF.pdf'],
			['course_id' => 2, 'title' => 'Persiapan RAT', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'RAT Persiapan (b vita).pdf'],
			['course_id' => 2, 'title' => 'Teknis Pelaksanaan RAT', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'konsep TEKNIS PELAKSANAAN RAT (p hotma).pdf'],
			['course_id' => 2, 'title' => 'Laporan Pertanggungjawaban Pengurus', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'LPJ PENGURUS psigit.pptx'],
			['course_id' => 2, 'title' => 'Laporan Pertanggungjawaban Pengawas', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'LHP dan LPJ Pengawasan  Jawara (p muluk)_compressed.pdf'],
			['course_id' => 2, 'title' => 'Pemilihan Pengurus dan Pengawas', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'Pemilihan Pengurus (p mario).pdf'],
			['course_id' => 3, 'title' => 'Pengantar Laporan Keuangan', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PENGANTAR LAP KEU VITA_compressed.pdf'],
			['course_id' => 3, 'title' => 'Penyusunan Laporan Keuangan', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PENYS LAP KEU RTN.pdf'],
			['course_id' => 3, 'title' => 'Praktek Penyusunan Laporan Keuangan', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PRAKTEK PENYS LAP KEU ELOK REV_compressed_compressed.pdf'],
			['course_id' => 3, 'title' => 'Analisa Rasio Keuangan Koperasi', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'Analisa Rasio Lap Keuangan_Heru.pdf'],
			['course_id' => 4, 'title' => 'Pengantar ADART', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PPT - PENGANTAR AD - ART.pdf'],
			['course_id' => 4, 'title' => 'Anggaran Dasar', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'AD_compressed.pdf'],
			['course_id' => 4, 'title' => 'Anggaran Rumah Tangga', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PPT ART OK.pdf'],
			['course_id' => 4, 'title' => 'Peraturan Khusus', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PERSUS.pdf'],
			['course_id' => 5, 'title' => 'Ketentuan Umum dan Tata Cara Perpajakan', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'KETENTUAN UMUM & TATA CARA PERPAJAKAN RIO.pdf'],
			['course_id' => 5, 'title' => 'Pajak Penghasilan', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PPH_Heru-compressed_compressed.pdf'],
			['course_id' => 5, 'title' => 'Pajak Pertambahan Nilai', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PPN_Heru-compressed.pdf'],
			['course_id' => 5, 'title' => 'Corporate Crime On Taxation', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'CORPORATE CRIME ON TAXATION RTN_compressed.pdf'],
			['course_id' => 5, 'title' => 'Tax Planning', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'TAX PLANNING ELOK.pdf'],
			['course_id' => 6, 'title' => 'Pengantar RK/RAPBK', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PENGANTAR RKRAPBK hotma.pdf'],
			['course_id' => 6, 'title' => 'Rencana Kerja Koperasi', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'Rencana Kerja Koperasi UUN (1)_compressed.pdf'],
			['course_id' => 6, 'title' => 'Rencana Anggaran Pendapatan dan Belanja Koperasi (Anggaran Kas dan Operasiona)', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'Rencana Anggaran Operasional dan Kas_elearning.pdf'],
			['course_id' => 6, 'title' => 'Evaluasi Rencana Kerja dan Rencana Anggaran Pendapatan dan Belanja Koperasi', 'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue mauris rhoncus aenean vel. Sed sed risus pretium quam vulputate. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Consequat nisl vel pretium lectus. Tempus iaculis urna id volutpat lacus laoreet non. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Netus et malesuada fames ac turpis egestas integer eget. Malesuada proin libero nunc consequat interdum varius. Nibh cras pulvinar mattis nunc. Purus semper eget duis at. Aliquet risus feugiat in ante metus.

Est ante in nibh mauris. Id venenatis a condimentum vitae sapien pellentesque habitant. Consequat id porta nibh venenatis cras. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Donec et odio pellentesque diam volutpat commodo sed egestas. Nunc sed blandit libero volutpat sed cras. Amet mattis vulputate enim nulla aliquet. Platea dictumst quisque sagittis purus sit amet. Convallis aenean et tortor at risus viverra adipiscing. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Vitae suscipit tellus mauris a diam. Phasellus faucibus scelerisque eleifend donec. Arcu non sodales neque sodales ut etiam. Sit amet consectetur adipiscing elit. Amet volutpat consequat mauris nunc. Diam donec adipiscing tristique risus nec feugiat in. Placerat in egestas erat imperdiet sed euismod.', 'module' => 'PPT - TIARA EVALUASI RK-RAPB KOPERASI.pdf'],
        ];

        foreach ($datas as $value) {
        	CourseContent::create($value);
        }
    }
}
